"use client";
import Head from "next/head";
import {useAuthModal} from "@/store/useAuthModal";
import AuthModal from "@/components/modals/AuthModal";

export default function Home() {
  const {isOpen, open, close, view, setView} = useAuthModal();
  
  return (
    <>
    <Head>
      <title>BrokeCode</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width-device-width, initial-scale=1"  />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <button onClick={() => {setView("login"); open();}}>Open auth</button>
      {isOpen && (
        <AuthModal view={view} onClose={close} onChangeView={setView} />
      )}
    </main>
    </>
  )
}