"use client";
import Head from "next/head";
import {useAuthModal} from "@/store/useAuthModal";
import AuthModal from "@/components/modals/AuthModal";
import Topbar from "@/components/Topbar";
import ProblemTable from "@/components/ProblemTable";
import {ToastContainer} from "react-toastify";

export default function Home() {
  const {isOpen, open, close, view, setView} = useAuthModal();
  
  return (
    <>
    <Head>
      <title>BrokeCode</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width-device-width, initial-scale=1"  />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="bg-[#1A1A1A] min-h-screen">
      <Topbar problemPage/>
        <h1 className="text-2xl text-center text-gray-700 dark:text-gray-400 font-medium uppercase mt-10 mb-5">WE ALL GO INSANE DOWN HERE</h1>

          <div className="relative overflow-x-auto mx-auto px-6 pb-10">
            <table className="text-sm text-left text-gray-500 dark:text-gray-400 sm:w-7/12 w-full max-w-[1200px] mx-auto">
              <thead className="text-xs text-gray-700 uppercase dark:text-gray-400 border-b">
                <tr>
                  <th scope="col" className="px-1 py-3 w-0 font-medium">
                    Status
                  </th>
                  <th scope="col" className="px-6 py-3 w-0 font-medium">
                    Title
                  </th>
                  <th scope="col" className="px-6 py-3 w-0 font-medium">
                    Difficulty
                  </th>
                  <th scope="col" className="px-6 py-3 w-0 font-medium">
                    Category
                  </th>
                  <th scope="col" className="px-6 py-3 w-0 font-medium">
                    Solution
                  </th>
                </tr>
              </thead>
              <ProblemTable />
            </table>
          </div>

      {isOpen && (
        <AuthModal view={view} onClose={close} onChangeView={setView} />
      )}
    </main>
    <ToastContainer position="top-right" autoClose={3000} theme="dark" />
    </>
  )
}